v24.11.12: Improvements to `update` command; Added `update diff`

diff --git a/my b/my
--- a/my
+++ b/my
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 __Author="Jerren Saunders"
-__Version=24.11.8
+__Version=24.11.12
 __ScriptName=$(basename "$0") # File name with extension
 __AppDir=$(dirname "$0") # Path where script is stored
 __AppName=${__ScriptName%.*} # File name without extension
@@ -58,16 +58,6 @@ VERBOSE=0
 DRYRUN=false
 MY_CUSTOM_FILE=.myCommand
 
-while getopts 'dv' option; do
-    # echo "Option: ${option}"
-    case ${option} in
-        d ) DRYRUN=true ;;
-        v ) VERBOSE=$((VERBOSE + 1)) ;;
-        * ) # Do Nothing
-    esac
-done
-shift $((OPTIND -1)) # Remaining args will be left
-
 # Prints log message to the terminal
 #  <int> lvl - Print Level: Only print this message if the VERBOSE level is greater than or equal to this
 #  <string> msg - Message to print
@@ -79,6 +69,20 @@ function log() {
         echo -e "$msg"
     fi
 }
+
+
+while getopts 'dv' option; do
+    # echo "Option: ${option}"
+    case ${option} in
+        d ) DRYRUN=true
+            log 0 "---- THIS IS A DRYRUN! ----\n"
+            ;;
+        v ) VERBOSE=$((VERBOSE + 1)) ;;
+        * ) # Do Nothing
+    esac
+done
+shift $((OPTIND -1)) # Remaining args will be left
+
 
 # Either runs the command or prints the command that would be executed if DRYRUN is 'true'
 #  <cmd> cmd - Command to execute or print
@@ -376,8 +380,6 @@ function findKey() {
 #  <string> key - The key to add
 #  <string> value - The value to associate with the key
 function set_key_value() {
-    if [[ "${DRYRUN}" == "true" ]]; then log 0 "---- THIS IS A DRYRUN! ----\n"; fi
-
     local key=$1
     shift
     local value="$1 " # The first element should always be a command so don't quote
@@ -438,8 +440,6 @@ function list_keys() {
 # Builds a merged version of the ${MY_CUSTOM_FILE} files in the directory tree
 # then if the give key is found, will execute the defined value
 function find_and_run_cmd() {
-    if [[ "${DRYRUN}" == "true" ]]; then log 0 "---- THIS IS A DRYRUN! ----\n"; fi
-
     # The command to search for
     cmd=$1
     shift
@@ -539,6 +539,79 @@ function find_and_run_cmd() {
     fi
 }
 
+
+# Update the script with the latest version
+function update_script() {
+    local arg="$2"
+    github_path=https://raw.githubusercontent.com/jerrens/MyCE/refs/heads/main/my
+    # install_path=/usr/local/bin/my
+    install_path=$0
+
+    # Check for internet access
+    if ! ping -q -c 1 -W 1 github.com >/dev/null; then
+        log 0 "No internet connection!"
+        exit 1
+    fi
+
+    # If 'diff' is requested, then download and show the diff
+    if [[ "$arg" == "diff" ]]; then
+        # Download the latest version from the github repo
+        local temp_file="/tmp/${__AppName}.new"
+
+        # Download the new version to a temp file
+        if ! runCMD curl --silent --location --output "${temp_file}" "${github_path}"; then
+            log 0 "Failed to download the latest version from $github_path"
+            exit 1
+        fi
+
+        if ! diff -q "${temp_file}" "${install_path}" >/dev/null; then
+            # Show the diff
+            log 0 "The following are the changes between your current version and the latest version on GitHub:\n"
+            sdiff -s --width=200 "${install_path}" "${temp_file}"
+
+            log 0 "\n---------------------------------------------------------------------------"
+            log 0 "You can run '${__ScriptName} update' to update to the latest version"
+        else
+            log 0 "You are already running the latest version!"
+        fi
+        log 0
+
+        # Remove the temp file
+        rm "${temp_file}"
+        exit 0
+    fi
+
+
+    if [ "$EUID" -ne 0 ]; then
+        log 0 "This should be run as root.  Attempting to elevate permissions..."
+
+        # Re-run this command as sudo
+        if command -v dzdo >/dev/null 2>&1; then
+            runCMD dzdo "$0" "$__origArgs"
+        else
+            runCMD sudo "$0" "$__origArgs"
+        fi
+        exit
+    fi
+    # NOTE: Root Level if here
+
+    # Download the latest version from the github repo
+    log 0 "\nDownloading latest version from GitHub..."
+    log 0 "    ${github_path}\n"
+
+    # Download the latest version of my
+    if ! runCMD curl --silent --location --output "${install_path}" "${github_path}"; then
+        log 0 "Failed to download the latest version from ${github_path}"
+        exit 1
+    fi
+
+    # Make it executable
+    log 0 "\nModifying permissions..."
+    runCMD chmod 755 "${install_path}"
+    log 0 "Update finished!"
+    exit 0
+}
+
 # Entry point of the program
 # Check the first arg to determine what action to take
 function main() {
@@ -579,32 +652,7 @@ function main() {
             ;;
 
         update)
-            if [ "$EUID" -ne 0 ]; then
-                log 0 "This should be run as root.  Attempting to elevate permissions..."
-
-	            #Re-run this command as sudo
-                if command -v dzdo >/dev/null 2>&1; then
-                    runCMD dzdo "$0" "$*"
-                else
-                    runCMD sudo "$0" "$*"
-                fi
-                exit
-            fi
-
-            # Root Level if here
-            github_path=https://raw.githubusercontent.com/jerrens/MyCE/refs/heads/main/my
-            log 0 "\nDownloading latest version from GitHub..."
-            log 0 "    $github_path\n"
-
-            # Download the latest version of my
-            curl --silent --output /usr/local/bin/my "$github_path"
-
-            # Make it executable
-            log 0 "\nModifying permissions..."
-            chmod 755 /usr/local/bin/my
-            log 0 "Update finished!"
-            exit 0
-            ;;
+            update_script "$@";;
 
         *)
             find_and_run_cmd "$@"
@@ -624,6 +672,8 @@ exit $?
 ######################################
 # shellcheck disable=SC2317  # Don't warn about unreachable commands in this function
 /dev/null <<EOT
+ - 24.11.12         Improvements to 'update' command handling.
+                    Added 'update diff' command.
  - 24.11.8          Added 'update' command
  - 24.11.7          Added support for positional args ($1, $2) within the .myCommand values
                     Always load the .myCommand file in the user home directory (even if not in current directory tree)
